
{
    ("INITIAL", "HELO"): "HELO_SENT",
    ("INITIAL", "EHLO"): "EHLO_SENT",
    ("HELO_SENT", "MAIL FROM:"): "MAIL_FROM_RECEIVED",
    ("EHLO_SENT", "MAIL FROM:"): "MAIL_FROM_RECEIVED",
    ("MAIL_FROM_RECEIVED", "RCPT TO:"): "RCPT_TO_RECEIVED",
    ("RCPT_TO_RECEIVED", "DATA"): "DATA_RECEIVED",
    ("DATA_RECEIVED", "."): "INITIAL",
    ("QUITTED", "QUIT"): "INITIAL"
}
